training_config:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  num_labels: 3
  output_dir: "project/results"
  batch_size: 8
  epochs: 5
  learning_rate: 0.0001
  seed: 42
  max_length: 128
  warmup_steps: 500

tokenizer:
  max_length: 384

wandb_config:
  project: "NLI_Project-org"
  entity: "NLI_Project"
  api: "f3b43f15e4b9d81f71b4be703dcc32e5d01189f2"