training_config:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  num_labels: "3"
  output_dir: "project/results"
  train_dataset: ""
  valid_dataset: ""
  test_dataset: ""
  batch_size: ""
  epochs: ""
  learning_rate: ""
  seed: ""
  max_length: ""
  warmup_steps: "500"

tokenizer:
  max_length: "384"

wandb_config:
  project: "diarization_finetuning_ina"
  entity: "dinum-dia"
  api: "f3b43f15e4b9d81f71b4be703dcc32e5d01189f2"